# Generated by Django 4.2.18 on 2025-01-21 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_createuserprofile"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CreateUserProfile",
            new_name="UserProfile",
        ),
    ]
