# Generated by Django 4.2.18 on 2025-01-21 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_postcomment_postlike"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="postlike",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="postlike",
            name="post",
        ),
        migrations.RemoveField(
            model_name="postlike",
            name="user",
        ),
        migrations.DeleteModel(
            name="PostComment",
        ),
        migrations.DeleteModel(
            name="PostLike",
        ),
    ]
